### ISSUE TITLE
Attendance at Meetings

### ISSUE THREAD

**Issue by acapozzol** [VenturaFranklin/thetatauCMT#140]
**Describe the bug**
When you create an event to track attendance at meetings, there is NO score

**To Reproduce**
1. Go to "Events"
2. Click on "Add Event"
3. Create an event and have the type of event be "Attendance at meetings"
4. Submit the event
5. See error

**Expected behavior**
All of the other events have no problem calculating a score, but "Attendance at meetings" always remains at 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/49173647/55366401-990c1e00-54b6-11e9-81f1-cf118a2a5ac2.png)

**Desktop**
 - OS: Windows 10
 - Browser: Google Chrome

I have played with the CMT on multiple occasions to see if there was any way to receive a score for meeting attendance, but nothing ever works.

**Comment by JonV12345** [comment]
Seeing this issue within another chapter as well
