### ISSUE TITLE
Multiple Member Statuses

### ISSUE THREAD

**Issue by carrle** [VenturaFranklin/thetatauCMT#21]
**Describe the bug**
Members are showing their current status as "active, pnm" or "pnm, active". Each member should only have one status. This occurred after the sync on 9/3/18.

**To Reproduce**
1. Go to cmt.thetatau.org
2. Choose a chapter (Delta and Chi Delta show this issue, as examples)
3. Click on Members
4. See error in "Current Status" column

**Expected behavior**
Each member should only show one status. "Active" or "pnm" instead of both.

**Screenshots**
![image](https://user-images.githubusercontent.com/34316031/45036304-1d361a00-b02a-11e8-9a20-df6848eb860a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 68.0.3440.106

**Comment by VenturaFranklin** [comment]
Closed by d3e9032d314ea1ebb73f4e2bbb6f174f9836f19f
