### ISSUE TITLE
Advisor/Oversight Officer Fields

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#212]
Can we add fields somewhere (not sure where this would fit best) where chapters can put in the name of their chapter adviser (usually an engineering prof or something) and the university official who has oversight over the chapter (F&SL office, student activities, etc.)

Ideally, once we move to the new semesterly report (the one where we're rolling the RM form, the NM program selection form, etc into a single paper document that they then upload) into the CMT (which I think we discussed?) it would be great if one of the questions on that form could be to re-enter the adviser and oversight officer so that it's regularly updated.

Thanks!

**Comment by VenturaFranklin** [comment]
Complete in cd111d426fe473d5c4d63db79d403325440b98f2
