### ISSUE TITLE
Add Submission - Name?

### ISSUE THREAD

**Issue by bargerc15** [VenturaFranklin/thetatauCMT#22]
Whose name? 
My name? 
Event Name? 
Submission Name? 

Intent of field need clarification. 
![image](https://user-images.githubusercontent.com/42555724/45065781-15f22900-b089-11e8-92fd-7c9a3cace508.png)

**Comment by VenturaFranklin** [comment]
I think dates make sense to specify, not name/description/type/score/everything/anything else, it just becomes too redundant and unnecessary.

**Comment by VenturaFranklin** [comment]
I was wrong, users have already put in their name for the name location. 
Hopefully all of the other fields will be clear enough...
