### ISSUE TITLE
Add Submission - Save Button

### ISSUE THREAD

**Issue by bargerc15** [VenturaFranklin/thetatauCMT#24]
Once all required fields are fulfilled, highlight "Save" button Green or Blue (dealer's choice). 

Read across to all submissions where "Save" is used. 

![image](https://user-images.githubusercontent.com/42555724/45066055-6ae26f00-b08a-11e8-88cc-e19982ddc746.png)

**Comment by VenturaFranklin** [comment]
"This field is required" lets someone know they missed a field. No need for extra enable/disable. 
Also I couldn't get it to work.
