### ISSUE TITLE
Updating Roles for Non Members? 

### ISSUE THREAD

**Issue by bargerc15** [VenturaFranklin/thetatauCMT#27]
There are roles that might be held by persons that are not members of the chapter let alone Theta Tau. Should they be listed as available roles? 

Employer / Ec
Faculty Adviser
House Corp Pres, Treas. 
Parent
President
Rube Goldberg (we don't have Rube Goldberg anymore)

**Comment by VenturaFranklin** [comment]
President is for some colonies, some chapters still have Rube Goldberg and chapters have Faculty Advisers, we add them to our system as a Pseudo member.
I think these are fine, just don't use them if you don't need them.

**Comment by VenturaFranklin** [comment]
Some people don't realize that president is not for them. Remove colony officer roles. They can get used to chapter roles.
