### ISSUE TITLE
Initiation Report

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#274]
Can you add a feature where I can filter and download data from the H&T website?  Even if I can't filter it and can just download it, that would be enormously helpful.

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT do you have a list of locations you would like to export? You have Initiation in the title, is this the only one?

**Comment by jimgaffneyTT** [comment]
Ideally I'd like to be able to export initiations, defers and (eventually
once it's in the CMT) pledges.

**Comment by VenturaFranklin** [comment]
Update to: MSCR and officer status

**Comment by VenturaFranklin** [comment]
Work in d74e8f4cbeff4817daae6272ab45d10a37cd2fbb

**Comment by jimgaffneyTT** [comment]
"DB Update" button crashes to a 500 screen when pressed.

Updating Theta Gamma's process - badge and shingle csv's downloaded fine, DB csv crashed out.
