### ISSUE TITLE
Custom Query Build

### ISSUE THREAD

**Issue by VenturaFranklin** [VenturaFranklin/thetatauCMT#277]
Custom queries on admin? (Must, low)

**Comment by VenturaFranklin** [comment]
https://gitlab.com/burke-software/django-report-builder
or
https://github.com/LegoStormtroopr/django-data-interrogator

**Comment by VenturaFranklin** [comment]
"hey how many withdrawals have we had this semester"
or "are we having more or less co-ops during the pandemic"
A dashboard would be great, but in the meantime, the ability to get a data dump and customize the data is more useful to me, I think
want to be able to pull one large list that says "we have x number of paying student members"
or "we have x number of pledges" or alums from alpha chapter, etc.  
Can get all of these data points from various places, but having one place where, when those other places don't give me what I need, I can go to get all of the data and drill it down in excel, is going to be easier than having to ask you for a bespoke report each time

**Comment by jimgaffneyTT** [comment]
Was going to open a new issue for this request but it dovetails nicely here.  Really, in the shortterm, the thing I need is for there to be an "export all student member" data, which would include all student members, including pledges, active, active pend, away.  From that list I can extrapolate almost anything I need.

What's listed above would still be preferable, so I can do more traditional data pulls (which we can do in Blackbaud.)
