### ISSUE TITLE
Pledge Program Update Form

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#285]
This form would be a one-off and (in all likelihood) would never need to be filled out again.

Questions would be:

1. Did you conduct new member education remotely after your campus went to remote instruction? [yes/no]
2. Which of the following is the case:
- We completed new member education and voted, we just have to initiate our pledges.
- We completed new member education but we still need to vote and initiate our pledges.
- We did not complete new member education.
3. If: We did not complete new member education, ask: How many weeks of new member education do you have yet to complete? [number]
4. When did New Member Education end; if it hasn't ended, please put the date at which you anticipate it ending? [date/can be in the future]
5. When did you/do you plan to initiate your Spring 2020 pledges?

We need to be able to see on a screen who has/has not filled out the report, the date it was filled out and who filled it out for the chapter.  It would also be great to have a "copy emails for the officers" button for Ernestine to follow up.

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT Ready for testing.

See form at https://venturafranklin.pythonanywhere.com/forms/pledgeprogram/
And the list report at: https://venturafranklin.pythonanywhere.com/forms/pledge-program-list/

Chapters that have already submitted the new version, but not the new new version will only have to update the new questions, but it still reports them as incomplete until they finish the question: "What is the current status of your new member education?*"

Copy Emails gets you a list of all emails to BCC email __after applying filter__. Or you can download CSV with officers by chapter.

**Comment by jimgaffneyTT** [comment]
This form looks great - please port to the live CMT.
