### ISSUE TITLE
Collection Referral Form

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#287]
Can we add a collections referral form to the CMT?  Accessible only to chapter officers, no workflow required, just submit and email to central.office.

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT  Do you have details for this? Should it just be a recreating of the current Word document? https://thetatauhq.publishpath.com/Websites/thetatauhq/images/Collection_Referral_Form2.doc

**Comment by jimgaffneyTT** [comment]
Correct, a recreation of the existing word doc.

**Comment by VenturaFranklin** [comment]
Work in f88e37cd29c2dacbd5792e3940f1224311867174 b51332f4abf85a8d41a2ccb768e633ba285bbfd1
