### ISSUE TITLE
OSM Application Workflow

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#289]
**URGENT**  We'd like to be able to release this on  5/8.

Chapter regent fills out form to nominate their chapter OSM for the national award:
Questions on form:

1. Select chapter member from dropdown list (self-nomination is allowed)
2. Date decision was made [date]
3. How was the Chapter Outstanding Student Member chosen?  What process was used to select them? [paragraph field]

Form should then be send to chapter VR and scribe to vefify - simple "yes, this is correct," "no, this isn't correct."

After verification, email should be sent to the nominated member with this link to fill out the application in SmarterSelect:  https://smr.to/p66110

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT ready for testing at: https://venturafranklin.pythonanywhere.com/osmform/

The officer emails you can see by submitting a test.

The officer verify page looks like this:
![image](https://user-images.githubusercontent.com/2513831/81196968-91019600-8f74-11ea-8352-e89bbd195e37.png)

The nomination email looks like this: https://venturafranklin.pythonanywhere.com/herald/11/html/

**Comment by VenturaFranklin** [comment]
Oh and a list of completed forms is at: https://venturafranklin.pythonanywhere.com/forms/osm-list/

**Comment by jimgaffneyTT** [comment]
Can you change the text on the form to say: 

Please use the form below to report which member of your chapter has been selected as the Outstanding Student Member (OSM).  Please enter the date of the meeting (or if done remotely, the date the vote was taken/selection was made) and select the brother who has been chosen as OSM.  Your chapter's Vice Regent and Scribe will receive an email asking them to verify the selection, and then the OSM will be sent an email with the link to apply for the national OSM award.

Otherwise, looks great.  Once that change has been made please move over to the live CMT and let me know the link.

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT 
I made a change to the wording/process that I think will be better:

> __Two other chapter officers* will receive an email asking them to verify the selection, and then the OSM will be sent an email with the link to apply for the national OSM award.
> *Depending on who submits the form and who is nominated officers that did not submit the form and are not nominated will be asked to verify.__

The order is first Regent --> VR --> Scribe --> Treasurer

Is now deployed to: https://cmt.thetatau.org/osmform

**Comment by jimgaffneyTT** [comment]
Looks good to me.
