### ISSUE TITLE
Alpha Chapter Members Missing? 

### ISSUE THREAD

**Issue by bargerc15** [VenturaFranklin/thetatauCMT#29]
Members in CMT.thetatau.org do not match the GSheets version. Please investigate.

**Comment by carrle** [comment]
I have the same issue with a few chapters in Great Lakes.

**Comment by VenturaFranklin** [comment]
I forgot about fall graduation dates. I set your grad date as the end for your active membership.
And assumed spring graduations.

**Comment by VenturaFranklin** [comment]
I should probably just have current active status go forever...no need to auto graduate members.

**Comment by VenturaFranklin** [comment]
All members listed as active in the CRM should be fixed
