### ISSUE TITLE
Landing Page within CMT That We Can Edit

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#290]
When you login to Kappa Sig's version of the CMT (they use a Salesforce community) you're greeted with a landing page with links to the most commonly-used forms and functions.  HQ will regularly edit that page to bump-up important links (convention registration, etc.)

Is it possible to implement something like this?

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT 
On the home page you can have an announcements section that would look like this:
![image](https://user-images.githubusercontent.com/2513831/91683647-0425ae00-eb0a-11ea-866f-2279fb0c4c9a.png)

In the admin page you have a section to add announcements. It is a WYSIWYG editor so it should be pretty close to Word? We will have to test and figure out. You can set the text, a start/end date for the announcement, and I'll add a priority so you can order the announcements to have several.
![image](https://user-images.githubusercontent.com/2513831/91683687-21f31300-eb0a-11ea-9a91-78328f97e03f.png)

The editor for the section is a [WYSIWYG editor](https://ckeditor.com/) which supports a bunch of capabilities. I say we start simple and we can discuss adding other features if/when you need them. But are there any features you know now you need?

How does this sound? Any questions or can you think of capabilities/needs for now?

**Comment by jimgaffneyTT** [comment]
This is AMAZING and exactly what I had in mind!  My only question is, does it support photos?  Like can I upload a photo for dislay?

 

My only suggestion is to make sure there’s a clear separation between one announcement and another – a dividing line or something.  I know with a lot of applications like this, and email editors, etc, the announcements bleed together.

**Comment by VenturaFranklin** [comment]
Added ability to add photos. 

In the picture you can see two announcments seperated by a gray line. Is that sufficient for "clear separation between one announcement and another" 
![image](https://user-images.githubusercontent.com/2513831/91921932-8e445280-ec81-11ea-94b8-49e9d6cd279c.png)

The dividers can be styled however
This is the default:
![image](https://user-images.githubusercontent.com/2513831/91922323-8d5ff080-ec82-11ea-8499-3ebfc04ce476.png)

Maybe this instead
![image](https://user-images.githubusercontent.com/2513831/91922281-6d303180-ec82-11ea-8ef8-845c52a07ccd.png)

**Comment by jimgaffneyTT** [comment]
I think go with the double-line as a separator.  Otherwise, perfect.
