### ISSUE TITLE
Make It Impossible to Postdate MSCR's/Initiations

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#295]
Can you make it impossible to post-date an MSCR?  Almost all of the MSCR changes you sent last week are for people who will (theoretically) graduate later this month and over the summer, which means that some of them probably won't graduate.  

Similarly, chapters are pre-reporting initiations, which I'm prohibited by Fraternal law from processing.

**Comment by VenturaFranklin** [comment]
I only did this for init/depledge. We always encourage chapters to submit grad, coop, study, etc. to be submitted as soon as you know they will happen.
