### ISSUE TITLE
Digitize Return to Student

### ISSUE THREAD

**Issue by VenturaFranklin** [VenturaFranklin/thetatauCMT#32]
Currently only way to return to student from alumni is emailing central?
And returning for prealumn is this form: https://thetatauhq.publishpath.com/Websites/thetatauhq/images/Return_to_student_status.doc
GanttStart: 2020-02-01
GanttDue: 2020-02-15

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT please provide details. The current method form is only for those who were alumn from pre-alumn.

Do we want to handle other alumn returning to student?

- Form submitted by officer --> 
- Email sent to submitter and member confirmation --> 
- Step to Exec Director review/approval --> 
- Email confirmation to member/officer confirmation on exec outcome

Any other steps in the process?

**Comment by jimgaffneyTT** [comment]
That process sounds right, and yes, it would only be for those who are listed as alumni in their chapter.  If it’s a member transferring from another school (like somebody who is starting grad school on a new campus and is affiliating with a new chapter) we’ll continue to do that manually, I feel like that’s a heavy lift in the CMT and only happens once or twice per year.
