### ISSUE TITLE
Natoff Member Search

### ISSUE THREAD

**Issue by VenturaFranklin** [VenturaFranklin/thetatauCMT#323]
Master Search Box where Natoff can type “John Smith” and it returns all of the John Smiths (not currently on the list)
first name, last name, full name, badge number, and email address
Filter by chapter/region
@jimgaffneyTT what information should the natoff be able to see?
Phone, email, address? status? (active/alumn/etc.) roles? (officer etc.)

**Comment by jimgaffneyTT** [comment]
NatOffs should be able to see everything.

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT This one should be good for review.
See: https://venturafranklin.pythonanywhere.com/users/search/

**Comment by jimgaffneyTT** [comment]
THIS IS AWESOME.  Ready to fly on the live site.
