### ISSUE TITLE
College in Exports

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#333]
Hey Frank,

For exports out of the django dashboard, can you make it so that it includes university name as a column as well?  TightRope uses college name not chapter designation, so whenever I have to shoot them out a report it takes forever to parse.

Fraternally,
Jim

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by VenturaFranklin** [comment]
Which exports?

**Comment by jimgaffneyTT** [comment]
When I export a report, such as a list of co-op forms submitted, or a list of depledges.  They give me chapter designation but not college.

**Comment by VenturaFranklin** [comment]
Got clarification on Jim on "Which exports" also includes those that are not in the back end.
Need to add university name to exports on table pages.
