### ISSUE TITLE
Add Premature Alums to the Graduate Report

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#368]
Can we add those students who go premature alum to the grad export you send every few weeks so that I can batch-process them into blackbaud?

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT Do you need to know what type of prealumn?
For the Reason for Status Change, I could have it be either 
Prealumn
or
Prealumn: less4/more4/grad
depending on the type of prealumn.

**Comment by jimgaffneyTT** [comment]
Nope, believe it or not, we separate out whether somebody is a regular alum or a prealum based on whether or not they have a degree.  So long as that field remains blank we’ll be able to tell who was a pre-alum.

**Comment by VenturaFranklin** [comment]
So, what should Reason for Status Change be?
