### ISSUE TITLE
Error 500 When Completing Pledge Workflow

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#377]
Hey Frank,

When I complete a pledge workflow (when I indicate that an invoice has been paid) I click "done" and then I jump to the 500 page within the CMT.  I did this last week with a "test" chapter pledge, and then again today with an Iota Epsilon live pledge class.

Thanks!

**Comment by ST3PHANI3** [comment]
Both Mu Epsilon's regent and I are getting this error too when we try to initiate our pledges.

**Comment by VenturaFranklin** [comment]
No need to open issues regarding 500 errors you get. 
Errors are automatically captured and logged.
#375
and
#376
