### ISSUE TITLE
"Last Updated" Date for Chapter Report

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#380]
Hey Frank,

Can you add a "last updated" data point on the "chapter" page on the front-end of the CMT?  We frequently mail things out of the CMT (awards, badges, shingles, etc) and need to know when the chapter most recently updated their address.  Sometimes these shipments are worth thousands of dollars, in the case of badges.

Fraternally,
Jim

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT Added on each chapter page under the chapter information section See: https://cmt.thetatau.org/chapters/phi-epsilon/
![image](https://user-images.githubusercontent.com/2513831/93965007-d7824200-fd15-11ea-82bb-913530bd5ce6.png)

**Comment by jimgaffneyTT** [comment]
AWESOME.  Thanks!
