### ISSUE TITLE
Pledge CSV Mapping Address

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#396]
Hey Frank,

The csv for the Pledge CRMUpdate is bunching the address up into a single field, it should be mapped this way, if possible:

Street Address
City
State
Zip

Thanks!

**Comment by VenturaFranklin** [comment]
Addresses suck to deal with: https://www.mjt.me.uk/posts/falsehoods-programmers-believe-about-addresses/

What are these addresses for? I think we need to provide details to the students why we need it, as some people are putting in address of their parents (eg. someone from Thailand) if this needs to be a mailing address, that's going to be a problem.

**Comment by jimgaffneyTT** [comment]
Strictly speaking we don’t use them for anything, but we’ve always asked for an address so we should continue to do so.  Can you edit the pledge form to specifically ask for a US address?
