### ISSUE TITLE
Test Chapter Status Change

### ISSUE THREAD

**Issue by manthacloud** [VenturaFranklin/thetatauCMT#40]
**Describe the bug**
When playing around the TEST chapter Status Change, real members names showed up from another chapter. Not sure if this is an issue only because it is "Test" or if this could happen to other chapters.

**To Reproduce**
1. Go to Status Change
2. Select random TestMember to change their status
3. Click Next
4. See error - Member name boxes turn red and show a drop down list of actual brother, not test subjects

**Expected behavior**
To change the status of the test member

**Screenshots**
See attached (I think?)

**Desktop:**
 - OS: Windows
 - Browser: Chrome

![test status change](https://user-images.githubusercontent.com/43152007/45328259-c8f6d280-b520-11e8-8fd0-0ba11f771473.png)

**Comment by VenturaFranklin** [comment]
I can not recreate this. Can you let me know and reopen this issue if you can recreate it.

**Comment by manthacloud** [comment]
I do not know how to re-open issues.



**Step 1** Log in
**Step 2** Go to change chapter by selecting TEST from dropdown and click Apply
![screenshot1](https://user-images.githubusercontent.com/43152007/45391543-0161e380-b5e9-11e8-97f8-017b10d0606a.png)
**Step 3** After clicking Apply, go to Home to refresh to the TEST Chapter Management Tool
![screenshot2](https://user-images.githubusercontent.com/43152007/45391544-0161e380-b5e9-11e8-8211-a6b24ff3b3f7.png)
**Step 4** Go to Forms dropdown and select Status Change Report
![screenshot3](https://user-images.githubusercontent.com/43152007/45391545-0161e380-b5e9-11e8-8997-0f6f7e7a812b.png)
**Step 5** Select random User from Test chapter and leave State option default of “Member is graduating”
**Step 6** Add row
**Step 7** Select another User for Row 2 and leave State option default of “Member is graduating”
![screenshot4](https://user-images.githubusercontent.com/43152007/45391546-01fa7a00-b5e9-11e8-9648-c64dbc765b3d.png)
**Step 8** Press Next and see issue
![screenshot5](https://user-images.githubusercontent.com/43152007/45391547-01fa7a00-b5e9-11e8-949b-cf7355696c29.png)
This is where the bug shows up. For some reason after pressing next, the User drop down turns red and the list goes from the Test members to actual names from another chapter.  I did manage to get through the form without issue when I switched the State option to be different than the default "member is graduating".
![screenshot6](https://user-images.githubusercontent.com/43152007/45391548-01fa7a00-b5e9-11e8-9d36-f052e64ba5f3.png)

**Comment by VenturaFranklin** [comment]
Still not resolved...
