### ISSUE TITLE
URGENT - Co-Ops Showing Up as Active

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#406]
Hey Frank,

Lambda Delta put in a bunch of co-ops in the Spring, for members who are away this Fall, but they're all showing up as "active" on the roster and on the reports we generated.  Their co-op forms look correct, they're dates properly, etc.

They submitted a co-op report for an additional student in August, and that student is showing up as away.

-Jim

**Comment by VenturaFranklin** [comment]
Determined this was issue with the CRM not storing members as away and when syncing would overwrite the CMTs away status as active.

I plan to go through all the away status change submissions, verify the member is marked as away
Then fix the sync to ignore the CRM while the member is away.
