### ISSUE TITLE
PDF Only

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#407]
Hey Frank,

Can you make it so that all document uploads into the CMT require PDF format?  

Fraternally,
Jim

**Comment by VenturaFranklin** [comment]
We can, but I'm concerned that students don't have scanners or pdf tools. Or do you want to force using a scanner to get better quality forms? Is there a specific reason why or something to fix? We could maybe convert uploads on our end?

**Comment by jimgaffneyTT** [comment]
It’s mostly selfish – I keep getting premature alumnus forms as word docs, which adds a couple of extra steps in reviewing them, when I know for a fact that both the windows and mac versions of word allow you to save as a PDF natively.
