### ISSUE TITLE
Chapter Page Not Updating After Changing Chapter And Clicking Apply

### ISSUE THREAD

**Issue by ablanchard887** [VenturaFranklin/thetatauCMT#41]
**Describe the bug**
On mine and Lindsey's screen (so as an RD); if you are on the chapter page for any given chapter (the page that shows the debt for the chapter as well as officers) and change to another chapter in the drop down in the top right and hit apply, then the name at the top changes but the chapter page itself does not refresh.

**To Reproduce**
1. Select a chapter from the drop down and click 'Apply'
2. Click on 'Chapter' 
3. Select a different chapter from the drop down and click 'Apply'

**Expected behavior**
Like the Members tab of a chapter, I expected for the chapter tab to refresh and load the new chapter after clicking apply

 - Windows 10 Pro
 - Chrome 
 - 68.0

**Comment by VenturaFranklin** [comment]
This is expected behavior.
The current page does not change and should not change. (It'd be a pain if you wanted to look at members/tasks/submissions/events/scores for each chapter and had to click that tab every time.) Chapter page is the only one like this.

**Comment by VenturaFranklin** [comment]
Turns out that this is not that hard to fix
