### ISSUE TITLE
Phantom Pledges - Epsilon Delta

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#420]
Gabriel Goins 
Narayan Gossai 
Ryan Ruffoni

Are appearing on Epsilon Delta's roster but are not from that chapter and I can't find a record of them having filled out the pledge form.

**Comment by VenturaFranklin** [comment]
Those three came from the old system and were synced from the CRM so I do
not have a pledge form for them.
It looks like the CRM had their chapter as Epsilon Delta but their school
as University of San Diego which is incorrect. They should be at Lambda
Epsilon which is USD.
