### ISSUE TITLE
Missing Brothers

### ISSUE THREAD

**Issue by manthacloud** [VenturaFranklin/thetatauCMT#43]
**From a chapter** 
"Our membership tab doesn't show our members that have been active for 5+ years "

Brothers who take longer than 4 years to graduate and are active for longer than their anticipated graduation date seem to be missing for a chapter.

Does this have to do with auto-graduating them?

**Comment by VenturaFranklin** [comment]
Those should have all been fixed. Who is missing? And from what chapters?

**Comment by manthacloud** [comment]
It was mentioned from Upsilon but I haven't gotten a list of names.  I can get those sent to the CMT email address

**Comment by manthacloud** [comment]
The Vice Regent is the one who told me there was an issue but I checked with the scribe and she said it looked like it was correct.
