### ISSUE TITLE
API Connection to MooSend

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#451]
Can we get the CMT connected to MooSend so that I can pull contacts directly from the CMT?

I.e. when I want to email chapter regents, I can pull a contemporaneous list without having to export from the CMT and manually import into MooSend.

**Comment by VenturaFranklin** [comment]
https://cmt.thetatau.org/report_builder/report/15
Maybe button on the report builder "send to moosend"
