### ISSUE TITLE
Initiation Workflow Step Revision

### ISSUE THREAD

**Issue by jimgaffneyTT** [VenturaFranklin/thetatauCMT#452]
Hey Frank, can we add a step to the initiation Workflow at the end, called "sales order received"? 

That workflow that should ask the user (whoever is interacting with the workflow) to input the "scheduled date" from the sales order and then generate an email to the chapter saying:

_"Herff Jones reports that your badge order will be shipped on (scheduled date). If you have not received your badges within two weeks of that date, please call the central office."_

Herff started providing us scheduled shipping dates for badge orders, so being able to report that data back to the chapter will be super helpful.

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT can there be a field in the current, "Badges ordered step?" for scheduled date or does it need to be a different step? Do they tell you right away the scheduled date or does it take some processing time that someone needs to come back to the system to add that info?

**Comment by jimgaffneyTT** [comment]
It takes a while - they physically mail us a piece of paper with the shipping date on it (I'm trying to get them to go paperless.)  Some badges ship within 72 hours of the order (unengraved badges) whereas the more expensive/complex ones take weeks/months.

Jim Gaffney,

Executive Director
He/Him/His
*************************************************
Theta Tau Central Office

175 SW 7th Street, Suite 1615

Miami, FL  33130


Ph: 512/472-1904
Fx: 512/472-4820
Em: jim.gaffney@thetatau.org [mailto:jim.gaffney@thetatau.org]

**************************************************

ENGINEERING LEADERS for Service, Profession, and Brotherhood
On 1/11/2021 9:39:40 AM, Franklin Ventura <notifications@github.com> wrote:
@jimgaffneyTT [https://github.com/jimgaffneyTT] can there be a field in the current, "Badges ordered step?" for scheduled date or does it need to be a different step? Do they tell you right away the scheduled date or does it take some processing time that someone needs to come back to the system to add that info?
