### ISSUE TITLE
Separate Tables for Chapter Officers

### ISSUE THREAD

**Issue by bargerc15** [VenturaFranklin/thetatauCMT#46]
have separate tables for Active Chapter Officers and Alumni Officers (housing corp, adviser(s), etc.)

**Comment by VenturaFranklin** [comment]
Why? What do you need to do?

**Comment by bargerc15** [comment]
Looking at a table with alumni can be confusing. Having separate tables will make finding the information we need faster.

**Comment by bargerc15** [comment]
To be honest I don't particularly need nor care to see who the alumni officers are unless I'm doing a visit.

**Comment by carrle** [comment]
Honestly, the only officers I've ever needed to look up, barring visits, are those listed in the ritual (and maybe pledge instructor). I think it would be beneficial to have the main officers listed separate from the extraneous ones, like committee chairs and alumni advisers.

**Comment by VenturaFranklin** [comment]
Does this not do what you need
https://cmt.thetatau.org/regions/great-lakes/officers/
And you can filter by the officers you look for?

**Comment by carrle** [comment]
It does, but not without extra motions. Maybe the default should be only those listed in ritual, then if we need the other officers, we can choose them from the list?
