### ISSUE TITLE
CMT Filters

### ISSUE THREAD

**Issue by aarndt14** [VenturaFranklin/thetatauCMT#476]
is it possible, from the Chapter Scores page, to change the semesters to filter for? Having future semesters doesn't seem to make sense. Could the future semesters be swapped with previous semesters? For example, right now I can see the latest completed semester (Fall 2020), the current in-progress semester (Spring 2021), and the two future semesters (Fall 2021 and Spring 2022). Could the list be Fall 2019, Spring 2020, Fall 2020, and Spring 2021?

**Comment by VenturaFranklin** [comment]
Likely need to review filters across the site

**Comment by VenturaFranklin** [comment]
This was originally done for the biennium. It was to encourage chapters to plan ahead, but also see how the chapter is scoring for the full biennium.
