### ISSUE TITLE
update jewelry prices

### ISSUE THREAD

**Issue by abe320** [VenturaFranklin/thetatauCMT#52]
update jewelry prices por favor

#102-Badge   with close set pearls, 10 karat gold | $179
#103-Badge   with crown set pearls, 10 karat gold | $219
#106-Badge   with crown set pearls, Vermeil | $69
#107-Badge   with crown set pearls, Gold-Filled/Layered | $121
#108-Brass   Badge with gold plating   | $38

**Comment by VenturaFranklin** [comment]
Done.
