### ISSUE TITLE
Graphs and Info on Dashboard (Home)

### ISSUE THREAD

**Issue by VenturaFranklin** [VenturaFranklin/thetatauCMT#8]
GanttStart: 2020-06-01
GanttDue: 2020-06-15

**Comment by VenturaFranklin** [comment]
Filters for: program directors view of specific PD events filter (select what you wnt)

**Comment by VenturaFranklin** [comment]
membership over time
    graduation over time for the chapter to see

**Comment by jimgaffneyTT** [comment]
Pledges from the current period (semester) who have been initiated
